language: python
python:
    - "3.7"
install:
    - pip install -r requirements.txt
script: 
    - nosetests --with-coverage --verbose --cover-package=generollup
notifications:
    email:
        - cgates@umich.edu
